config/routes.rb
=begin

Lesli

Copyright (c) 2020, Lesli Technologies, S. A.

All the information provided by this website is protected by laws of Guatemala related 
to industrial property, intellectual property, copyright and relative international laws. 
Lesli Technologies, S. A. is the exclusive owner of all intellectual or industrial property
rights of the code, texts, trade mark, design, pictures and any other information.
Without the written permission of Lesli Technologies, S. A., any replication, modification,
transmission, publication is strictly forbidden.
For more information read the license file including with this software.

Lesli - Your Smart Business Assistant

Powered by https://www.lesli.tech
Building a better future, one line of code at a time.

@contact  <hello@lesli.tech>
@website  <https://lesli.tech>
@license  Propietary - all rights reserved.

// · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
// · 

=end

Rails.application.routes.draw do

  namespace :account do
    resources :activities
  end
    devise_for :users,
    :path => "",
    :path_names => {
        :sign_in  => "login",
        :sign_out => "logout",
        :sign_up  => "register",
        :password => "password",
        :confirmation => "confirmation"
    },
    :controllers => { 
        :registrations => "users/registrations",
        :confirmations => "users/confirmations",
        :passwords => "users/passwords",
        :sessions => "users/sessions"
    }

    get :language, to: "application#switch_locale"

    extend RoutesBuilder
    extend RoutesApp

    authenticated :user do

        mount ActionCable.server  => "/cable"
        mount CloudBell::Engine   => "/bell"   if defined?(CloudBell)
        mount CloudLock::Engine   => "/lock"   if defined?(CloudLock)
        mount CloudPanel::Engine  => "/panel"  if defined?(CloudPanel)
        mount CloudLesli::Engine  => "/lesli"  if defined?(CloudLesli)
        mount CloudBabel::Engine  => "/babel"  if defined?(CloudBabel)
        mount CloudHouse::Engine  => "/house"  if defined?(CloudHouse)
        mount CloudFocus::Engine  => "/focus"  if defined?(CloudFocus)
        mount CloudNotes::Engine  => "/notes"  if defined?(CloudNotes)
        mount CloudDriver::Engine => "/driver" if defined?(CloudDriver)
        mount CloudMailer::Engine => "/mailer" if defined?(CloudMailer)

        root to: redirect("/dashboard"), as: :root_authenticated

    end

    mount CloudDispatcher::Engine => "/api" if defined?(CloudDispatcher)

    match "/404", :to => "errors#not_found",             :via => :all
    match "/401", :to => "errors#unauthorized",          :via => :all
    match "/500", :to => "errors#internal_server_error", :via => :all

    root to: "websites#show", as: :root_unauthenticated

end

app/views/layouts/partials/_application-analytics.html.erb
<% if Rails.env == "production" %>
<!-- Analytics -->
<script type="text/javascript">

    var _paq = window._paq || [];
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);

    (function() {

        var u = "//analytics.lesli.tech/";

        _paq.push(['setTrackerUrl', u + 'matomo.php']);
        _paq.push(['setSiteId', '2']);

        var d=document, 
            g=d.createElement('script'), 
            s=d.getElementsByTagName('script')[0];

        g.type='text/javascript'; 
        g.async=true; 
        g.defer=true; 
        g.src=u+'matomo.js'; 
        s.parentNode.insertBefore(g,s);

    })();
    
</script>
<!-- End Analytics Code -->
<% end %>

app/views/layouts/partials/_application-assets-js.html.erb
<%#

Lesli

Copyright (c) 2020, all rights reserved.

All the information provided by this platform is protected by international laws related  to 
industrial property, intellectual property, copyright and relative international laws. 
All intellectual or industrial property rights of the code, texts, trade mark, design, 
pictures and any other information belongs to the owner of this platform.

Without the written permission of the owner, any replication, modification,
transmission, publication is strictly forbidden.

For more information read the license file including with this software.

// · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
// · 


%>

<% translation_timestamp = File.mtime(Rails.root.join("public", "javascripts", "translations.js")).to_i %>
<%= javascript_include_tag "i18n" %>
<%= javascript_include_tag "translations?#{translation_timestamp}", skip_pipeline: true %>
<%= javascript_include_tag application_javascript_path() %>
 
<script>

    // Set language for JavaScripts apps
    I18n.locale = '<%= I18n.locale %>'

</script>

<script src="//js.honeybadger.io/v2.2/honeybadger.min.js" type="text/javascript"></script>
<script type="text/javascript">
Honeybadger.configure({
    apiKey: "<%= Rails.application.credentials.services[:honey_badger][:api_key] %>",
    revision: "<%= @account[:revision][:version] %>-<%= @account[:revision][:build] %>",
    environment: "<%= Rails.env %>",
    disabled: <%= !Rails.env.production? %>
})
</script>

app/views/layouts/partials/_application-layout-content.html.erb
<application-component-search></application-component-search>
<%= yield %>

app/views/layouts/partials/_application-layout-header.html.erb
<%#

Lesli

Copyright (c) 2020, Lesli Technologies, S. A.

All the information provided by this website is protected by laws of Guatemala related 
to industrial property, intellectual property, copyright and relative international laws. 
Lesli Technologies, S. A. is the exclusive owner of all intellectual or industrial property
rights of the code, texts, trade mark, design, pictures and any other information.
Without the written permission of Lesli Technologies, S. A., any replication, modification,
transmission, publication is strictly forbidden.
For more information read the license file including with this software.

Lesli - Your Smart Business Assistant

Powered by https://www.lesli.tech
Building a better future, one line of code at a time.

@contact  <hello@lesli.tech>
@website  <https://lesli.tech>
@license  Propietary - all rights reserved.

// · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
// · 

%>

<application-component-header>

    <%# Custom header from builder engine %>
    <% if lesli_instance != "lesli" %>
    <%= render partial: "layouts/#{lesli_instance.underscore}/partials/module-app-header" %>
    <% end %>

    <%# username %>
    <template v-slot:username>
    <%= current_user.full_name %>
    </template>

    <%# show language selector for development only %>
    <% if not Rails.env.production? %>
    <template v-slot:languages>
        <div class="dropdown is-hoverable">
            <div class="dropdown-trigger">
                <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
                    <span class="icon has-text-grey-light">
                        <%= flag_icon(language_flag(I18n.locale)) %>
                    </span>
                </button>
            </div>
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
                <div class="dropdown-content">
                    <% I18n.available_locales.each do |locale| %>
                        <% next if locale == I18n.locale %>
                        <%= link_to language_url(locale), { :class => "dropdown-item" } do %>
                            <span class="icon has-text-grey-light">
                                <%= flag_icon(language_flag(locale)) %>
                            </span>
                            <span><%= language_name(locale) %></span>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </template>
    <% end %>

</application-component-header>

app/views/layouts/partials/_application-layout-module.html.erb
<%#

Lesli

Copyright (c) 2020, Lesli Technologies, S. A.

All the information provided by this website is protected by laws of Guatemala related 
to industrial property, intellectual property, copyright and relative international laws. 
Lesli Technologies, S. A. is the exclusive owner of all intellectual or industrial property
rights of the code, texts, trade mark, design, pictures and any other information.
Without the written permission of Lesli Technologies, S. A., any replication, modification,
transmission, publication is strictly forbidden.
For more information read the license file including with this software.

Lesli - Your Smart Business Assistant

Powered by https://www.lesli.tech
Building a better future, one line of code at a time.

@contact  <hello@lesli.tech>
@website  <https://lesli.tech>
@license  Propietary - all rights reserved.

// · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
// · 

%>

<application-component-module>
    <%# Custom module navigation from builder engine %>
    <% if lesli_instance != "lesli" %>
    <%= render partial: "layouts/#{lesli_instance}/partials/platform-module-navigation" %>
    <% end %>
</application-component-module>

app/views/layouts/partials/_application-layout-navigation.html.erb
<%#

Lesli

Copyright (c) 2020, Lesli Technologies, S. A.

All the information provided by this website is protected by laws of Guatemala related 
to industrial property, intellectual property, copyright and relative international laws. 
Lesli Technologies, S. A. is the exclusive owner of all intellectual or industrial property
rights of the code, texts, trade mark, design, pictures and any other information.
Without the written permission of Lesli Technologies, S. A., any replication, modification,
transmission, publication is strictly forbidden.
For more information read the license file including with this software.

Lesli - Your Smart Business Assistant

Powered by https://www.lesli.tech
Building a better future, one line of code at a time.

@contact  <hello@lesli.tech>
@website  <https://lesli.tech>
@license  Propietary - all rights reserved.

// · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
// · 

%>

<application-component-navigation>
    <%# Custom navigation from builder engine %>
    <% if lesli_instance != "lesli" %>
    <%= render partial: "layouts/#{lesli_engine_or_instance}/partials/module-app-navigation" %>
    <% end %>
</application-component-navigation>

app/views/layouts/partials/_application-layout-sidebar.html.erb
<%#

Lesli

Copyright (c) 2020, Lesli Technologies, S. A.

All the information provided by this website is protected by laws of Guatemala related 
to industrial property, intellectual property, copyright and relative international laws. 
Lesli Technologies, S. A. is the exclusive owner of all intellectual or industrial property
rights of the code, texts, trade mark, design, pictures and any other information.
Without the written permission of Lesli Technologies, S. A., any replication, modification,
transmission, publication is strictly forbidden.
For more information read the license file including with this software.

Lesli - Your Smart Business Assistant

Powered by https://www.lesli.tech
Building a better future, one line of code at a time.

@contact  <hello@lesli.tech>
@website  <https://lesli.tech>
@license  Propietary - all rights reserved.

// · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
// · 

%>

<application-component-sidebar>

    <%# Custom navigation from builder engine %>
    <% if lesli_instance != "lesli" %>
    <%= render partial: "layouts/#{lesli_instance.underscore}/partials/module-app-brand" %>
    <%= render partial: "layouts/#{lesli_engine_or_instance}/partials/module-app-navigation" %>
    <% end %>
</application-component-sidebar>

app/views/layouts/partials/_application-public-asset-js.html.erb
<%#

Lesli

Copyright (c) 2020, Lesli Technologies, S. A.

All the information provided by this website is protected by laws of Guatemala related 
to industrial property, intellectual property, copyright and relative international laws. 
Lesli Technologies, S. A. is the exclusive owner of all intellectual or industrial property
rights of the code, texts, trade mark, design, pictures and any other information.
Without the written permission of Lesli Technologies, S. A., any replication, modification,
transmission, publication is strictly forbidden.
For more information read the license file including with this software.

Lesli - Your Smart Business Assistant

Powered by https://www.lesli.tech
Building a better future, one line of code at a time.

@contact  <hello@lesli.tech>
@website  <https://lesli.tech>
@license  Propietary - all rights reserved.

// · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
// · 

%>

<% translation_timestamp = File.mtime(Rails.root.join("public", "javascripts", "translations.js")).to_i %>
<%= javascript_include_tag "i18n" %>
<%= javascript_include_tag "translations?#{translation_timestamp}", skip_pipeline: true %>

<script>
    // Set language for JavaScripts apps
    I18n.locale = "<%= I18n.locale %>"
</script>


<%# Load specific javascript files for devise actions (login,register,etc) %>
<% if controller_path.split('/')[0] == "users" %>
<%= javascript_include_tag controller_path %>
<% end %>


<%# Load standard files %>
<% if controller_path.split('/')[0] != "users" %>
<%= javascript_include_tag application_javascript_path() %> 
<% end %>

app/views/layouts/partials/_application-public-assets-js.html.erb
<%#

Lesli

Copyright (c) 2020, Lesli Technologies, S. A.

All the information provided by this website is protected by laws of Guatemala related 
to industrial property, intellectual property, copyright and relative international laws. 
Lesli Technologies, S. A. is the exclusive owner of all intellectual or industrial property
rights of the code, texts, trade mark, design, pictures and any other information.
Without the written permission of Lesli Technologies, S. A., any replication, modification,
transmission, publication is strictly forbidden.
For more information read the license file including with this software.

Lesli - Your Smart Business Assistant

Powered by https://www.lesli.tech
Building a better future, one line of code at a time.

@contact  <hello@lesli.tech>
@website  <https://lesli.tech>
@license  Propietary - all rights reserved.

// · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
// · 

%>

<% translation_timestamp = File.mtime(Rails.root.join("public", "javascripts", "translations.js")).to_i %>
<%= javascript_include_tag "i18n" %>
<%= javascript_include_tag "translations?#{translation_timestamp}", skip_pipeline: true %>

<script>
    // Set language for JavaScripts apps
    I18n.locale = "<%= I18n.locale %>"
</script>


<%# Load specific javascript files for devise actions (login,register,etc) %>
<% if controller_path.split('/')[0] == "users" %>
<%= javascript_include_tag controller_path %>
<% end %>

<%# Load standard files %>
<% if controller_path.split('/')[0] != "users" %>
<%= javascript_include_tag application_javascript_path() %> 
<% end %>

app/views/layouts/partials/_application-public-notify.html.haml
- if notice
    .notification.is-primary
        %p= notice
- if alert
    .notification.is-warning
        %p= alert

app/views/layouts/partials/_application_alert.html.haml
- if notice
    %p.alert.alert-success= notice
- if alert
    %p.alert.alert-danger= alert

app/views/layouts/partials/_application_asset_css.html.haml
- css_controller = controller_path
- css_controller_action = [controller_path,action_name].join('/')

= stylesheet_link_tag css_controller, media: 'all'        if Rails.application.assets.find_asset("#{css_controller}.scss")
= stylesheet_link_tag css_controller_action, media: 'all' if Rails.application.assets.find_asset("#{css_controller_action}.scss")

app/views/layouts/partials/_application_head.html.haml
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%meta{:charset => "utf-8"}/
%meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
%title LesliCloud • Your smart business assistant
= csrf_meta_tags
= csp_meta_tag
/%link{:href => "/assets/img/brand/favicon.png", :rel => "icon", :type => "image/png"}/

app/views/layouts/partials/_application_public-footer.html.haml
%footer
    %nav.navbar{"aria-label" => "main navigation", :role => "navigation"}
        .navbar-brand
            %a.navbar-item{:href => "https://lesli.cloud"} 
                LesliCloud

        .navbar-menu
            .navbar-start
            .navbar-end
                %a.navbar-item
                    Privacy